[tool.poetry]
name = "deep_temple"
version = "0.1.0"
description = "Another deep learning template"
authors = ["melandur <account@qunit.ch>"]
license = "MIT"

[tool.poetry.dependencies]
loguru = "^0.6.0"

monai = "^0.8.1"

numpy = "^1.22.3"

python = "^3.9"
pytorch-lightning = "^1.6.1"

setuptools = "^62.1.0"


[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pylint = "^2.13.7"
vulture = "^2.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"


