[tool.poetry]
name = "deep_temple"
version = "0.1.0"
description = "Another deep learning template"
authors = ["melandur <account@qunit.ch>"]
license = "MIT"

[tool.poetry.dependencies]
gdown = "^4.4.0"

loguru = "^0.6.0"

itk = "^5.2.1"

nibabel = "^3.2.2"

numpy = "^1.22.3"

Pillow = "^9.1.0"
python = "^3.9"
pytorch-lightning = "^1.6.1"

setuptools = "^62.1.0"
h5py = "^3.7.0"
torchio = "^0.18.77"
pytorch-ignite = "^0.4.9"
torchvision = "^0.12.0"
monai = "^0.8.1"
rich = "^12.4.4"
matplotlib = "^3.5.2"
autohooks = "^22.7.2"


[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pylint = "^2.13.7"
vulture = "^2.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.autohooks]
mode = "poetry"
pre-commit = ["autohooks.plugins.isort", "autohooks.plugins.black"]



