[tool.poetry]
name = "abyss"
version = "0.1.0"
description = "here to learn"
authors = ["melandur <account@qunit.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

loguru = "^0.7.2"
numpyencoder = "^0.3.0"
h5py = "^3.10.0"
matplotlib = "^3.8.3"
torch = {url = "https://download.pytorch.org/whl/cu121/torch-2.2.1%2Bcu121-cp312-cp312-linux_x86_64.whl", markers = "sys_platform == 'linux'"}
monai = "^1.3.0"
torchio = "0.19.1"
rich = "^13.7.1"
torchmetrics = "^1.3.1"

[tool.poetry.dev-dependencies]
black = "^24.2.0"
isort = "^5.13.2"
pylint = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
