[tool.poetry]
name = "abyss"
version = "0.1.0"
description = "Another deep learning template"
authors = ["melandur <account@qunit.ch>"]
license = "MIT"


[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.0.0"
torchvision = "^0.15.1"
torchaudio = "^2.0.1"
urllib3 = "1.26.15"
wandb = "^0.15.1"
lightning = "^2.0.2"
monai = "^1.1.0"
loguru = "^0.7.0"
matplotlib = "^3.7.1"
h5py = "^3.8.0"
torchio = "^0.18.91"
numpyencoder = "^0.3.0"


[tool.poetry.group.dev.dependencies]
autohooks = "^23.4.0"
autohooks-plugin-black = "^23.4.0"
autohooks-plugin-pylint = "^23.4.0"
autohooks-plugin-isort = "^23.4.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.autohooks]
mode = "pythonpath"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.isort", "autohooks.plugins.pylint"]


[tool.black]
line-length = 120
skip-string-normalization = true


[tool.isort]
profile = "black"
